'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace MeishiWeb

    Partial Public Class analytiic
        Public Property ANAID As Integer
        Public Property DateCreated As String
        Public Property email As String
        Public Property area As String
        Public Property name As String
        Public Property count As Integer
    
    End Class

End Namespace
