'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace MeishiWeb

    Partial Public Class CardInfo
        Public Property CardID As Integer
        Public Property DetailID As String
        Public Property CompanyID As String
        Public Property StreetName As String
        Public Property AddressLine As String
        Public Property Province As String
        Public Property PostalCode As String
        Public Property Country As String
        Public Property DisplayName As String
        Public Property CompanyLogo As String
        Public Property Company_moto As String
        Public Property AgentName As String
        Public Property Introduction As String
        Public Property FirstName As String
        Public Property MiddleName As String
        Public Property LastName As String
        Public Property [Alias] As String
        Public Property Bio As String
        Public Property JobTitle As String
        Public Property Location As String
        Public Property ProfilePic As String
        Public Property email As String
        Public Property WebSite As String
        Public Property Facebook As String
        Public Property Instagram As String
        Public Property Twitter As String
        Public Property LinkedIn As String
        Public Property YouTube As String
        Public Property LandLineNumber As String
        Public Property MobileNumber As String
        Public Property FaxNumber As String
        Public Property CompanyName As String
        Public Property ActiveAccount As String
        Public Property CompanyBot As String
        Public Property PersonBot As String
    
    End Class

End Namespace
