'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace MeishiWeb

    Partial Public Class CardDBEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=CardDBEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property CardLinks() As DbSet(Of CardLink)
        Public Overridable Property analytiics() As DbSet(Of analytiic)
        Public Overridable Property CardInfoes() As DbSet(Of CardInfo)
    
    End Class

End Namespace
