'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace MeishiWeb

    Partial Public Class CardLink
        Public Property LinkID As Integer
        Public Property CompanyID As String
        Public Property Title1 As String
        Public Property LinkName1 As String
        Public Property Title2 As String
        Public Property LinkName2 As String
        Public Property Title3 As String
        Public Property LinkName3 As String
        Public Property Title4 As String
        Public Property LinkName4 As String
        Public Property Title5 As String
        Public Property LinkName5 As String
        Public Property Title6 As String
        Public Property LinkName6 As String
        Public Property Title7 As String
        Public Property LinkName7 As String
        Public Property Title8 As String
        Public Property LinkName8 As String
        Public Property Title9 As String
        Public Property LinkName9 As String
        Public Property Title10 As String
        Public Property LinkName10 As String
        Public Property Title11 As String
        Public Property LinkName11 As String
        Public Property Title12 As String
        Public Property LinkName12 As String
        Public Property Title13 As String
        Public Property LinkName13 As String
        Public Property Title14 As String
        Public Property LinkName14 As String
        Public Property Title15 As String
        Public Property LinkName15 As String
        Public Property CardID As String
    
    End Class

End Namespace
